function [calTables, calTableTitles] = CalibrationTable(cal_script)
    % APPENDIXTABLES is capable of generating tables to be used in the appendix
    %   of the report generated by SDD_Report.
    %   This function can be modified to work as desired by the user.
    %   However, the interface of this function should not be altered else
    %   changes would need to be made where this function is called within
    %   SDD_Report.rpt.
    %   The default of this function will not create any tables.
    %
    %   Two example functions have been created to generate appendix tables,
    %   they may be useful to help figure out how to make another function or
    %   they may help to see what could be inlcuded in the appendix.
    %
    %   Inputs:
    %       cal_script      MATLAB script specified in
    %                       Report_Specific_Files/TopsysName_SDD_Config.
    %
    %   Outputs:
    %       calTables      A cell array of 1 x n matrices of 1 x 1 cell
    %                      arrays. Each row of the tables that will be
    %                      generated is represented by a 1 x n matrix in
    %                      the appendixTables cell array.
    %       calTableTitles Provides a title to correspond with tables in
    %                      appendixTables.
    
    calTables = {};
    calTableTitles = {};
    
    %Table of variables from file (e.g. a calibration file)
    [calTables{end+1}, calTableTitles{end+1}] = tableFromVarsInFile(cal_script,'Calibrations');
    
end

function [appendixTable, appendixTableTitle] = tableFromVarsInFile(script,title)
    %Prepares a table listing variables which are declared at the end of a call to another MATLAB script
    %   The tables will give the variable name with their type and value
    
    %Example case in which this could be used:
    %   The system being documented has a calibration file of some sort
    %   associated with it
    
    %Note this actually runs the given file.
    
    %title is a char indicating what the title of the table should be
    %script is the MATLAB file which will be run
    
    tableHeader = [{'Name'}, {'Data Type'}, {'Value'}];
    appendixTable = tableHeader;
    appendixTableTitle = title;
    
    currentVariables = who; % Variables already on the path
    currentVariables{end+1} = 'currentVariables';
    run(script);
    newVariables = setdiff(who,currentVariables); % These are the variables we want to include in the appendix in this case
    
    for i = 1:length(newVariables)
        var = newVariables{i};
        dataType = class(eval(var));
        value = eval(var);
        appendixTable = [appendixTable; {var}, {dataType}, {value}];
    end
end